$background = rgb(040607)
$foreground = rgb(E5ECF0)
$color0 = rgb(040607)
$color1 = rgb(0E1619)
$color2 = rgb(0F181C)
$color3 = rgb(263E4D)
$color4 = rgb(263E4D)
$color5 = rgb(3B7098)
$color6 = rgb(8896A0)
$color7 = rgb(D2DBE2)
$color8 = rgb(93999E)
$color9 = rgb(121D21)
$color10 = rgb(142025)
$color11 = rgb(335367)
$color12 = rgb(335367)
$color13 = rgb(4E95CA)
$color14 = rgb(B6C8D5)
$color15 = rgb(D2DBE2)
